"""fix some relations

Revision ID: b15cd4fdd3ac
Revises: c6503bc9cb2a
Create Date: 2023-11-23 00:51:41.871605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15cd4fdd3ac'
down_revision: Union[str, None] = 'c6503bc9cb2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
