"""delete subtasks on task delete

Revision ID: dd74a8ceb863
Revises: f08a83cffec6
Create Date: 2023-11-25 17:49:02.497295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd74a8ceb863'
down_revision: Union[str, None] = 'f08a83cffec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_parent_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_parent_id_fkey', 'tasks', 'tasks', ['parent_id'], ['id'])
    # ### end Alembic commands ###
