"""user ondelete relations

Revision ID: 25214714bb98
Revises: dd74a8ceb863
Create Date: 2023-11-25 18:21:23.718690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25214714bb98'
down_revision: Union[str, None] = 'dd74a8ceb863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('member_project_project_id_fkey', 'member_project', type_='foreignkey')
    op.create_foreign_key(None, 'member_project', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('member_task_task_id_fkey', 'member_task', type_='foreignkey')
    op.create_foreign_key(None, 'member_task', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('member_team_team_id_fkey', 'member_team', type_='foreignkey')
    op.create_foreign_key(None, 'member_team', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('member_workspace_workspace_id_fkey', 'member_workspace', type_='foreignkey')
    op.create_foreign_key(None, 'member_workspace', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member_workspace', type_='foreignkey')
    op.create_foreign_key('member_workspace_workspace_id_fkey', 'member_workspace', 'workspaces', ['workspace_id'], ['id'])
    op.drop_constraint(None, 'member_team', type_='foreignkey')
    op.create_foreign_key('member_team_team_id_fkey', 'member_team', 'teams', ['team_id'], ['id'])
    op.drop_constraint(None, 'member_task', type_='foreignkey')
    op.create_foreign_key('member_task_task_id_fkey', 'member_task', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'member_project', type_='foreignkey')
    op.create_foreign_key('member_project_project_id_fkey', 'member_project', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
