"""user ondelete relations

Revision ID: adf82b32da8d
Revises: 25214714bb98
Create Date: 2023-11-25 18:24:00.507359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf82b32da8d'
down_revision: Union[str, None] = '25214714bb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('member_project_member_id_fkey', 'member_project', type_='foreignkey')
    op.create_foreign_key(None, 'member_project', 'users', ['member_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('member_task_member_id_fkey', 'member_task', type_='foreignkey')
    op.create_foreign_key(None, 'member_task', 'users', ['member_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('member_team_member_id_fkey', 'member_team', type_='foreignkey')
    op.create_foreign_key(None, 'member_team', 'users', ['member_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('member_workspace_member_id_fkey', 'member_workspace', type_='foreignkey')
    op.create_foreign_key(None, 'member_workspace', 'users', ['member_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member_workspace', type_='foreignkey')
    op.create_foreign_key('member_workspace_member_id_fkey', 'member_workspace', 'users', ['member_id'], ['id'])
    op.drop_constraint(None, 'member_team', type_='foreignkey')
    op.create_foreign_key('member_team_member_id_fkey', 'member_team', 'users', ['member_id'], ['id'])
    op.drop_constraint(None, 'member_task', type_='foreignkey')
    op.create_foreign_key('member_task_member_id_fkey', 'member_task', 'users', ['member_id'], ['id'])
    op.drop_constraint(None, 'member_project', type_='foreignkey')
    op.create_foreign_key('member_project_member_id_fkey', 'member_project', 'users', ['member_id'], ['id'])
    # ### end Alembic commands ###
