"""substaks changed from many to many to one to many relationship

Revision ID: 685dd7e2bc70
Revises: b15cd4fdd3ac
Create Date: 2023-11-24 12:31:33.442662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685dd7e2bc70'
down_revision: Union[str, None] = 'b15cd4fdd3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtasks')
    op.add_column('tasks', sa.Column('parent_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'parent_id')
    op.create_table('subtasks',
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], name='subtasks_child_id_fkey'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name='subtasks_parent_id_fkey'),
    sa.PrimaryKeyConstraint('child_id', 'parent_id', name='subtasks_pkey')
    )
    # ### end Alembic commands ###
